# -*- mode: org; org-confirm-babel-evaluate: nil; org-speed-commands-user: nil; org-use-speed-commands: t; -*-
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../css/special-block.css" />
#+HTML_HEAD: <link href="http://thomasf.github.io/solarized-css/solarized-dark.min.cs" rel="stylesheet"></link>
#+HTML_HEAD: <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
#+HTML_HEAD: <script src="http://127.0.0.1:60000/autoreload.js"></script>



#+OPTIONS: toc:nil h:1


#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}

#+LATEX_HEADER:  \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amsfonts}

#+LATEX_HEADER: \newcommand{\Problem}[1]{\subsection*{Problem #1}}
#+LATEX_HEADER: \newcommand{\Q}[1]{\subsubsection*{Q.#1}}
#+LATEX_HEADER: \newcommand{\union}[1]{\underset{#1}{\cup} }
#+LATEX_HEADER: \newcommand{\bigunion}[1]{\underset{#1}{\bigcup} \, }
#+LATEX_HEADER: \newcommand{\inter}[1]{\underset{#1}{\cap} }
#+LATEX_HEADER: \newcommand{\biginter}[1]{\underset{#1}{\bigcap} }
#+LATEX_HEADER: \newcommand{\minimize}[3]{\optimize{#1}{#2}{#3}{min}}
#+LATEX_HEADER: \newcommand{\maximize}[3]{\optimize{#1}{#2}{#3}{max}}
#+LATEX_HEADER: \DeclareMathOperator{\cov}{cov}
#+LATEX_HEADER: \DeclareMathOperator{\var}{var}

#+BEGIN_SRC emacs-lisp :exports none
(defun add-caption-header-and-center (caption header )
  (concat (format "org\n#+attr_html: :class center\n#+caption: %s\n%s\n#+ATTR_LATEX: :float nil" caption header)))
(defun add-caption-and-center (caption)
  (concat (format "org\n#+attr_html: :class center\n#+caption: %s\n#+ATTR_LATEX:  :width 0.35\\textwidth :float nil" caption)))

#+END_SRC

#+RESULTS:
: add-caption-and-center


#+TITLE: Problem set 9, ORF527
#+AUTHOR: Bachir El khadir

* Q1
  *a.*
  - $W_{t+\tau} - W_{\tau}$ is $F_{\tau+t}$ -measurable, and is 0 when $t=0$
  - for all $w$, $t \rightarrow W_{t+\tau(\omega)}(\omega) - W_{\tau(\omega)}$ is continuous
  - For all $r$
    \begin{align*}
    E[e^{i r(W_{t+\tau} - W_{\tau+s})} | F_{\tau+s}]
    &= \int e^{ir(x-W_{\tau+s})} \frac{e^{-(x-W_{\tau+s})^2/2(t-s)}}{\sqrt{2\pi (t-s)}} dx
    & \text{(Strong Markov)}
    \\&= \int e^{irx} \frac{e^{-x^2/2(t-s)}}{\sqrt{2\pi (t-s)}} dx
    \\&= E[e^{ir\sqrt{t-s}N}] & \text{(Where $N \sim \mathcal N(0, 1)$)}
    \\&= e^{-\frac{r^2}2(t-s)} 
    \end{align*}
    Which proves that $W_{t+\tau}-W_{s+\tau} \sim N(0, t-s) \perp F_{s+\tau}$

  *b.*

  By Steele 9.2, there exist $Y_t = f(X_t)$ with $f$ invertible and $a(.)$ such that:
  $Y_t = Y_0 + \int_0^t a(Y_s) ds + W_t$

  Let $\tilde Y_t = Y_{t+\tau}$

  $B_t = W_{\tau + t} - W_{\tau}$


  \begin{align*}
  \tilde Y_t &= Y_{\tau} + + \int_{\tau}^{t+\tau} a(Y_s) ds + W_{t+\tau} - W_{\tau}
  \\&= \tilde Y_0 + \int_0^\tau a(\tilde Y_s) ds + B_t
  \end{align*}
  So $\tilde Y_t$ is the solution to :
  $d\tilde Y_t = a(\tilde Y_t) dt + dB_t$

  So $\tilde Y_t - \tilde Y_0$ is measurable with respect to $(\mathcal F^B_t)$
  In particular, since $(W_{t + \tau} - W_\tau)_{t \ge 0} \perp F_{\tau}$, $F_t^B \perp F_{\tau}$
  
  \begin{align*}
  E[g(X_{t+\tau}) | F_{\tau}] &= E[ g\circ f^{-1}(Y_{t+\tau}) | F_{\tau}]
  \\&= E[ g\circ f^{-1} (\tilde Y_t - \tilde Y_0 + \tilde Y_0) | F_{\tau}]
  \\&= E[ g\circ f^{-1} (\underbrace{ \tilde Y_t - \tilde Y_0}_{\perp F_{\tau}} + \underbrace{\tilde Y_0}_{F_{\tau}-\text{measurable}})  | F_{\tau}]
  \\&= E[ g\circ f^{-1} (\tilde Y_t - \tilde Y_0 + \tilde Y_0)  | \tilde Y_0]
  \\&= E[ g\circ f^{-1} (Y_{t+\tau})  | Y_\tau]
  \\&= E[ g(X_{t+\tau})  | X_\tau]
  \end{align*}

  
  
* Q2
  a. Ito formula applied to $f(x+W_t)$ when $t \le \tau^x$:
  
  \begin{align*}
  f(x+W_t)
  &= f(x) + \int_0^t \nabla f(x+W_s)dW_s + \int_0^t \frac12 \Delta f(x+W_s)ds
  \\&= f(x) + \int_0^t \nabla f(x+W_s)dW_s - \int_0^t g(x+W_s)ds
  \end{align*}
  So:
 $$E[\phi(x+W_{\tau^x})] = E[f(x+W_{\tau^x})] = f(x) + E[\int_0^{\tau_x} \nabla f(x+W_s)dW_s] - \int_0^{\tau_x} g(x+W_s)ds]$$
 
We have that  $E[\int_0^{\tau_x} |\nabla f(x+W_S)|^2] \le |\nabla f|^2_{\infty B(0, 1)} V(B(0, 1))$, so $\int_0^{\tau_x} \nabla f(x+W_s)dW_s$ is a martingale and has expectation 0.
   
So:
 $$f(x) = E[\int_0^{\tau_x} g(x+W_s)ds + \phi(x+W_{\tau^x})]$$



*b*
Let $f(x) = -\frac1{n} ||x||^1$, so that $\frac11 \Delta f(x) = 1$, $f(x) = -\frac1{n}$ when $||x||=1$

By part *a*: $f(x) = E[\tau^x - \frac1n ]$, so that $$E[\tau^x] = \frac1{n}(1 - ||x||^2)$$

*Q3*

$f(X_t) = f(0) + \int_0^t \nabla f(X_s)^Tb(X_s)ds + \int_0^t \nabla f(X_s)^T \sigma(X_s)dB_s + \int_0^t\sum_{i, j, k} \sigma^{ik}\sigma^{jk}\frac{\partial}{\partial  x_ix_j}f)(X_s) ds$

 \begin{align*}  E[\int_0^t \nabla f(X_s)^Tb(X_s) ds]
  &= \int_0^t E[\nabla f(X_s)^Tb(X_s)] ds &\text{(Fubini)}
  \\&= \int_0^t \int_x \nabla f(x) b(x) p(x,s) dx ds
  \\&= \sum_{i=1}^d \int_0^t \int_x  \partial_i f(x) b_i(x) p(x,s) dx ds
  \\&= - \int_0^t \int_x   f(x)  \sum_{i=1}^d \partial_i (b_ip(.,s))(x) dx ds &\text{(bc $f$ has compact support)}
  \end{align*}


 \begin{align*}
 E[\int_0^t\sum_{i, j, k} (\sigma^{ik}\sigma^{jk}\frac{\partial}{\partial  x_ix_j}f)(X_s) ds]
 &= \int_0^t\sum_{i, j, k} \int_x (\sigma^{ik}\sigma^{jk}\frac{\partial^2}{\partial  x_ix_j}f)(x) p(x, s)ds
 \\&= - \int_0^t\sum_{i, j, k} \int_x (\frac{\partial \sigma^{ik}\sigma^{jk} p(., s)}{\partial  x_j} \frac{\partial}{\partial  x_i}f)(x) ds
 \\&=  \int_0^t\sum_{i, j, k} \int_x (\frac{\partial^2 \sigma^{ik}\sigma^{jk} p(., s)}{\partial x_i x_j} f)(x) dxds
 \end{align*}
 
$E[f(X_t)] = f(0) + \int_0^t \int_x f(x) \mathcal L^*p(s, x) dx ds$

\begin{align*}
\partial_t E[f(X_t)] &= \partial_t \int_x f(x) p(x, s) ds\\
&=  \int_x f(x) \partial_t p(x, s) dx\\
\end{align*}

$\partial_t \int_0^t \int_x f(x) \mathcal L^*p(s,x) dx ds = \int_0^t \int_x f(x) \mathcal L^*p(s,x) dx$

We conclude that for every $f$, $C^2$, bounded, and with compact support:
$\int_x f(x) \left[\partial_t p(s, x) - \mathcal L^*p(s,x)\right] dx =  0$

If for some $x$, $\partial_t p(x, s) \ne \mathcal L^*p(s,x)$, then by continuity there exist all ball around $x$ $B$ where this function keep a constant sign (WLOS positive sign).

Let $f$ be a $C^{\infty}$ function with support $B$, positive on ball $B' \subseteq $B$, then:
$\int_{x \in \mathbb R^d}  f(x) \left[\partial_t p(s, x) - \mathcal L^*p(s,x)\right] dx = \int_{x \in B'}  f(x) \left[\partial_t p(s, x) - \mathcal L^*p(s,x)\right] dx >  0$
Absued.

So $\partial_tp(x, t) = \mathcal L^*p(x, s)$

* Q4


  First Let's prove that it's enough to prove the result for $f$ with compact support.

  Indeed, let $f \in C^2$, and let $\phi \in C^{\infty}$ the function defined by:
  \[\phi(x) = \left\{  \begin{array}{cc}
  1 &\text{if } ||x|| \in [0, 1]
  \\0 &\text{if } ||x|| \in [2, \infty)
  \end{array}
  \right.
  \]

  Consider $f_n(x) = \phi(\frac{x}n)f(x)$, then $f_n$ is $C^2$ has compact support, and equal to $f$ on $B(0, n)$. 

  $$f_n(W_t) = f_n(0) + \int_0^t f_n'(W_s)dW_s + \int_0^t \frac12 f''(W_s)ds$$
  
  Let $\tau_n$ be the first time $W_t$ hits $B(0, n)$, then, for $t < \tau_n$, 
  $$f(W_t) = f(0) + \int_0^t f_n'(W_s)dW_s + \int_0^t \frac12 f''(W_s)ds$$

  Note that since $f(W_t)$ is continuous, $\tau_n \uparrow \infty$, (otherwise $f(W_t)$ would blow up in fintie time), and therefore the last eqaulity is valid for any $t > 0$ by letting $n$ go to $\infty$.

  Now we consider only the case where $f$ ahs compact support $K$.


  WLOS $x_1 < \ldots < x_k$ and $K = [x_1, x_k]$
  Consider $f_n''$ definied as follow.
  
  \[
  f_n''(x) = \left\{\begin{array}{cc}
  f''(x_j-\frac1n) + \frac{x-x_j-\frac1n}{1/n}(f''(x_j^-) - f''(x_j-\frac1n)) & \text{if } x \in [x_{j} - \frac1n, x_j]\\
  \\f''(x) &  \text{otherwise}
  \end{array}\right.
  \]

  Notice that $f_n''(x)$ is continuous and converges pointwise to $f''$ except in the $x_j$

  
  $f_n'(x) = f'(x_1) + \int_{x_1}^x f_n''(y)dy$

    $f'(x_k + \frac1n) - f'(x_1) = \int_{x_1}^{x_k+\frac1n} f_n''(x)$
    
    When $x \in [x_1, x_n]$:
  \begin{align*}|f_n'(x)  - f'(x)| &= |\sum_{j=2}^k \int_{x_{j-1}}^{x_j \wedge x} f_n''(y) - f''(y) dy|
  \\&= |\sum_{j=2}^k \int_{x_{j-1}}^{x_j-\frac1n} f_n''(y) - f''(y) dy +  \int_{(x_j-\frac1n)\wedge x}^{x_j\wedge x} f_n''(y) - f''(y) dy|
  \\&= |\sum_{j=2}^k \int_{(x_j-\frac1n)\wedge x}^{x_j\wedge x} f_n''(y) - f''(y) dy|
  \\&\le k \frac{2M}{n}
  \end{align*}

Take $g_n' = \phi(\frac x n) f_n(x)$
Note that when $n > |x_n| \vee |x_1|$, 

  So $|f_n' - f'|_{\infty} \rightarrow 0$

  $f_n(x) = f(x_1) + \int_0^x f_n'(y)dy$

  $$|f_n - f|_{\infty} \le \int_{x_1}^{x_n} |f_n'(y) - f'(y)| \le \frac{2k|x_k - x_1|M}{n} \rightarrow 0$$
  

  Note that when $t < \tau_n$
  $f_n(W_t) = f_n(0) + \int_0^t f_n'(W_s)dW_s + \frac12 \int_0^t f_n''(W_s)ds$

  - $f_n(W_s) \rightarrow f(W_s)$ a.s
  - $f_n(0) \rightarrow f(0)$
  - $|f_n'(W_s) - f'(W_s)|_{L_2} \le ||f_n' - f'||_{\infty} \rightarrow 0$, so $\int_0^t f_n'(W_s)dW_s \overset{L_2}{\rightarrow} \int_0^t f'(W_s)dW_s$
  - $|f_n''|_\infty \le |f_n|_\infty \le M$, and $f_n''(W_s) \overset{as}\rightarrow f''(W_s)$ by dominated convergence theorem, $\int_0^t f_n''(W_s) ds \overset{as}{\rightarrow} \int_0^t f_n''(W_s)ds$
    
    In particular, all the convergences hold in probability, so for all $t$ (since $\tau_n \rightarrow \infty$)
    $f(W_t) = f(0) + \int_0^t f'(W_s) + \frac12 \int_0^t f''(W_s)ds$















